### ISSUE TITLE
getCordinates() should be getCoordinates()

### ISSUE THREAD

**Issue by stephane-caron** [jrl-umi3218/sch-core#14]
There is a typo in `include/sch/S_Polyhedron/S_PolyhedronVertex.h`. The function name should be `getCoordinates()` (it took me a while to figure out why I couldn't text search for this function...)

**Comment by gergondet** [comment]
Sure, I'll get a patch out tomorrow. I think we'll keep `getCordinates()` and deprecate it in order not to break existing code that might be using it for now.

**Comment by gergondet** [comment]
Fixed in 6a7466d
