### ISSUE TITLE
Build error on missing install destination

### ISSUE THREAD

**Issue by orikuma** [jrl-umi3218/sch-core#15]
When I tried to build sch-core but got following errors in current master (f59bd62b05d195a06fbf9367b66d4c68dca0e166) with drcutil (https://github.com/jenkinshrg/drcutil).
I succeeded in building sch-core by checking out 48cd6c3.
How can I fix this problem?

```bash
cmake '-DCMAKE_INSTALL_PREFIX=/home/iori/openrtp' '-DCMAKE_BUILD_TYPE=Release' '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON' '-DCMAKE_C_FLAGS= ' '-DCMAKE_CXX_FLAGS=-g ' '' ..
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   serialization
CMake Error at src/CMakeLists.txt:93 (install):
  install FILES given no DESTINATION!


-- Doxygen rendering: using LaTeX backend
CMake Error at CMakeLists.txt:56 (SETUP_PROJECT_PACKAGE_FINALIZE):
  Unknown CMake command "SETUP_PROJECT_PACKAGE_FINALIZE".


-- Configuring incomplete, errors occurred!
See also "/home/iori/src/sch-core/build/CMakeFiles/CMakeOutput.log".
make: *** ターゲット `install' を make するルールがありません.  中止.

```

**Comment by haudren** [comment]
I am not sure about your setup, but the current github master points to f814b56 , not f59bd62 . 

I am unable to reproduce the bug on my machine so it must be related to your setup. What distribution are you running ? What version of cmake ? Can you check that it is not related the flags you pass in (i.e. try a naked `cmake ..`) ?

Can you make sure that the git submodules are up-to-date ? (`git submodule update --init` will do the trick).

**Comment by haudren** [comment]
By the way, if your goal is to have optimized binaries with debug info, the appropriate build type is `RelWithDebInfo` instead of using `Release` with `-g`.

**Comment by orikuma** [comment]
I could solve this problem by updating submodules (`git submodule update --init`).
Thank you for your advice.

**Comment by gergondet** [comment]
Is this on a clean clone? I can reproduce if I checkout/clone 5c3796f51ed7f0ef37a7add338e1b41c8fe06f7d then pull master but keep the old cmake submodule commit.  

You need to update the submodule

**Comment by gergondet** [comment]
Ok, nevermind, you figured it out :+1:
