### ISSUE TITLE
CD_Pair accuracy (_PRECISION_ and _EPSILON_) and NaN with STPBV

### ISSUE THREAD

**Issue by jorisv** [jrl-umi3218/sch-core#4]
I have some issues with the precision of sch.

When I make a distance query between two hulls, if I repeat the query multiple times (at least twice time) and set
the same configuration to the two hulls, I can obtain a slightly different positions of the closes points.

This is really disturbing for nonlinear optimization, because that can break the continuity of the gradient.

I have been looking at the `_PRECISION_` and `_EPSILON_` values in CD_Pair.cpp (https://github.com/jrl-umi3218/sch-core/blob/master/src/CD/CD_Pair.cpp#L18-L19).
I feel like `_PRECISION_` is not well set.
In the constructor of `CD_Pair`, `precision_` copies the value of `_PRECISION_` but in `CD_Pair::setRelativePrecision`
`precision_` is set to the square of the precision given as a parameter.
Also, default `_EPSILON_` value is far from the real machine epsilon on 64-bits systems. Why not use `std::numeric_limits<double>::epsilon()` instead of hard-coding it ?

By calling `setRelativePrecision(1e-6)` and `setEpsilon(std::numeric_limits<double>::epsilon())` (https://github.com/jorisv/PG/blob/master/src/CollisionConstr.cpp#L96-L97) I obtain "better" results (precision-wise) for the closest-point query and my optimization process.

The only issue I have with this solution is when I start using STPBVs. In that case, `CD_Pair` can return NaN…
It appears that `CD_Pair::{det_,lambda0_,lambda1_,lambda2_}` values are set to -inf (https://github.com/jrl-umi3218/sch-core/blob/master/src/CD/CD_Pair.cpp#L232-L235).

I still can't have the guarantee to have a continuous gradient by using convex hulls, but the result is still better than when using STPBVs with standard epsilon and precision.

**Comment by mehdi-benallegue** [comment]
This bug concerns an old version after which, NaN issues have been fixed by f32a846c37b94a790385e14399b32fb91992c22e
