### ISSUE TITLE
Compiling against boost 1.76.0+ requires C++11

### ISSUE THREAD

**Issue by BenjaminNavarro** [jrl-umi3218/sch-core#44]
Starting from Boost 1.76 the `boost/math/constants/constants.hpp` header requires C++11 to be built ([gotbolt](https://godbolt.org/z/T14xdj74v)).

I don't know if you prefer to require C++11 for sch-core (at least when boost 1.76+ is used) or to remove this header and implements workarounds to keep C++98 compatibility.

**Comment by gergondet** [comment]
Hi @BenjaminNavarro 

I'm aware of the issue and for now I have adopted the temporary solution to pass `-DCMAKE_CXX_STANDARD=11` when building sch-core. That's definitely not ideal though.

I'm in favor of losing the dependence on the boost/math header (regardless of Boost version) as we only need pi from that.
